/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbcd",
        "secondary-container": "#6cf8bb",
        "on-error-container": "#93000a",
        "primary-container": "#2563eb",
        "error-container": "#ffdad6",
        "surface-container": "#ededf9",
        "on-surface-variant": "#434655",
        "on-surface": "#191b23",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "primary": "#004ac6",
        "primary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#360f00",
        "inverse-surface": "#2e3039",
        "on-primary-container": "#eeefff",
        "inverse-on-surface": "#f0f0fb",
        "outline": "#737686",
        "on-secondary-fixed": "#002113",
        "on-secondary-container": "#00714d",
        "on-primary": "#ffffff",
        "background": "#faf8ff",
        "on-primary-fixed": "#00174b",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-container": "#ffede6",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#943700",
        "surface": "#faf8ff",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#003ea8",
        "surface-variant": "#e1e2ed",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb596",
        "surface-tint": "#0053db",
        "secondary": "#006c49",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-highest": "#e1e2ed",
        "surface-container-high": "#e7e7f3",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-background": "#191b23",
        "surface-dim": "#d9d9e5",
        "inverse-primary": "#b4c5ff",
        "surface-bright": "#faf8ff",
        "tertiary-container": "#bc4800",
        "surface-container-low": "#f3f3fe",
        "outline-variant": "#c3c6d7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "0.25rem",
        "lg": "1.5rem",
        "2xl": "3rem",
        "sm": "0.5rem",
        "gutter": "1.5rem",
        "xl": "2rem",
        "md": "1rem",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "h1": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "h3": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "600"}],
        "h2": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
